import { useDesigns } from "@/hooks/use-designs";
import { DesignCard } from "@/components/DesignCard";
import { Loader2 } from "lucide-react";
import { Link } from "wouter";

export default function Gallery() {
  const { data: designs, isLoading, error } = useDesigns();

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <Loader2 className="w-8 h-8 animate-spin text-white/50" />
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center text-center px-4">
        <h2 className="text-2xl font-display text-white mb-2">Error Loading Gallery</h2>
        <p className="text-muted-foreground mb-4">Could not fetch designs.</p>
        <button 
          onClick={() => window.location.reload()} 
          className="px-6 py-2 bg-white text-black font-bold uppercase tracking-wider text-sm hover:bg-gray-200"
        >
          Retry
        </button>
      </div>
    );
  }

  return (
    <div className="min-h-screen py-12 px-4 container mx-auto">
      <div className="flex flex-col md:flex-row justify-between items-end mb-12 gap-4">
        <div>
          <h1 className="text-4xl md:text-5xl font-display mb-2">Design Gallery</h1>
          <p className="text-muted-foreground font-light">Explore recent creations generated by AI.</p>
        </div>
        
        <Link href="/generate">
          <button className="px-6 py-3 border border-white/20 text-white text-xs font-bold uppercase tracking-widest hover:bg-white hover:text-black transition-all">
            + Create New
          </button>
        </Link>
      </div>

      {designs && designs.length > 0 ? (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
          {designs.map((design) => (
            <DesignCard key={design.id} design={design} />
          ))}
        </div>
      ) : (
        <div className="py-20 text-center border border-dashed border-white/10 rounded-lg">
          <p className="text-muted-foreground mb-6">No designs found yet.</p>
          <Link href="/generate">
            <button className="px-8 py-3 bg-white text-black font-bold uppercase tracking-widest hover:bg-gray-200">
              Be The First
            </button>
          </Link>
        </div>
      )}
    </div>
  );
}
